config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => "user/registrations" }

	namespace :api, defaults: {format: 'json'} do 
  		namespace :v1 do
  			resources :users, :controllers => {:my_friends => "user/my_friends"}
			resources :users, :controllers => {:show => "user/show"}
  			resources :posts, :controllers => {:create => "posts/create"}
        resources :friendships

        # map.resources :users, :path_names => {:my_friends => 'my_friends'}
        get 'my_friends', to: 'users#my_friends'
        get 'show', to: 'users#show'
        post 'create', to: 'posts#create'

  		end
  	end
  	
	resources :users, only: [:show]
	resources :friendships
	resources :posts

	root 'welcome#index'
	get 'my_friends', to: 'users#my_friends'
	get 'search_friends', to: 'users#search'
	post 'add_friend', to: 'users#add_friend'
	get 'my_posts', to: 'users#my_posts'
	get 'view_friend', to: 'users#view_friend'
	get 'news_feed', to: 'users#news_feed'
	post 'authenticate', to: 'authentication#authenticate'
	get 'test', to: 'welcome#test'
	get 'test2', to: 'welcome#test2'
	 #api auth token

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ActiveRecord::Base #ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
	acts_as_token_authenticatable
	devise :database_authenticatable, :registerable,
		:recoverable, :rememberable, :trackable, :validatable

	
    mount_uploader :avatar, AvatarPicUploader
  	
  	has_many :friendships  
  	has_many :friends, through: :friendships
  	has_many :posts     

	#has_secure_password

	def full_name
    	return "#{first_name} #{last_name}".strip if (first_name || last_name) 
    	"Anonymous"
  	end

	def not_friends_with?(friend_id)
		friendships.where(friend_id: friend_id).count < 1
	end

	def except_current_user(users)
		users.reject {|user| user.id == self.id}
	end

	def self.search(param)
		return User.none if param.blank?
		param.strip!
		param.downcase!
		(first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
	end

	def self.first_name_matches(param)
		matches('first_name', param)
	end

	def self.last_name_matches(param)
		matches('last_name', param)
	end

	def self.email_matches(param)
		matches('email', param)
	end

	def self.matches(field_name, param)
		where("lower(#{field_name}) like ?", "%#{param}%")
	end

	def authenticate(submitted_password)
	  self.valid_password?(submitted_password)
	end

end

app/controllers/api/v1/users_controller.rb
module Api
	module V1
		class UsersController < ApplicationController
			respond_to :json	

			def index	#all users
				@users = User.all
				render json: {status: 'SUCCESS', message:'Loaded Users', data:@users}, status: :ok
			end

			def show #show 1 user
				#@user = User.find(params[:id])
				@user = @current_user
				render json: {status: 'SUCCESS', message:'Loaded User', data:@user}, status: :ok
			end

			def create #create new user
				#respond_with Post.create(params[:friendship])
			end
		
			def update #edit user profile
				#respond_with Post.update(params[:id], params[:friendship])
			end
			
			def destroy #destroy user account
				#respond_with Post.destroy(params[:id])
			end

			def my_friends #a users friends
				@all_users = User.all
				@api_user = @current_user ####uses last user in list, need to change
				#@friendships = @api_user.friends
				@friendships = @api_user.friends
				#@friendships = @all_users  #currently shows all users ##change w/tokens
				render json: {status: 'SUCCESS', message:'Loaded friendships', data:@friendships}, status: :ok
			end


			def my_posts #all my posts
			end

			def news_feed #posts from my friends only
			end
		end
	end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
	before_action :configure_permitted_parameters

	protected

	#def configure_permitted_parameters
	#	devise_parameter_sanitizer.for(:sign_up).push(:first_name, :last_name)
	#	devise_parameter_sanitizer.for(:account_update).push(:first_name, :last_name)
	#end

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :avatar])
		devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :avatar])
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	# def my_portfolio
	# 	@user_stocks = current_user.stocks
	# 	@user = current_user
	# end

	def my_friends
		 @friendships = current_user.friends
		# respond_to do |format|
		# 	format.html
		# 	format.json { render json: @friendships }
		# end
	end

	def search
		@users = User.search(params[:search_param])
		if @users
			@users = current_user.except_current_user(@users)
			render partial: 'friends/lookup'
		else
			render status: :not_found, nothing: true
		end
	end

	def add_friend
		@friend = User.find(params[:friend])
		current_user.friendships.build(friend_id: @friend.id)
		if current_user.save
			redirect_to my_friends_path, notice: "Friend was successfully added."
		else
			redirect_to my_friends_path, flash[:error] = "There was an error with adding user as friend."
		end
	end

	def my_posts
		@user = current_user
		@posts = current_user.posts
		# @user_stocks = @user.user_stocks
	end

	def view_friend
		@current_friend = User.find(params[:friend])
	end

	def news_feed
		@posts = Post.all
		@all_posts = Post.all
		@all_posts.each do |post|
			if current_user.not_friends_with? post.user.id
				@posts -= [post]
			else
				#we are friends

			end
		end
				#@user = User.where(email: params[:user])
	end
	
	def show
		@user = User.find(params[:id])
	end
end

app/views/users/my_friends.html.erb
<%= render 'friends/lookup' %>
<% if @friendships.size > 0 %>
	 <table class="table table-striped">
		<thead>
		<tr>
			<th colspan="3" class="page-header">
			<h2>My Friends</h2>
			</th>
		</tr>
		<tr>
			<th>Name</th>
			<th>Email</th>
			<th>Actions</th>
		</tr>
		</thead>
		<tbody>
			<% @friendships.each do |friend| %>
				<tr>
					<td><%= friend.full_name %></td>
					<td><%= friend.email %></td>
					<td>
						<%= link_to "View Posts", view_friend_path(friend: friend), class: "btn btn-primary btn-xs" %>
						<%= link_to 'Remove Friend', friendship_path(friend),
						:method => :delete, :data => { :confirm => 'Are you sure?' },
						:class => 'btn btn-xs btn-danger' %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
<% else %>
	<div class='row col-lg-12'>
		<p class="lead">You don't have any friends yet. Please add some!</p>
	</div>
<% end %>

app/views/users/my_posts.html.erb
<div class="container container-table">
	<h2>My Posts</h2>
	<table class="table table-bordered text-center">
		<tbody>
			<% @posts.each do |post| %>
				<tr>
					<div class="card cd" style="width: 40rem">
						<div class="card-header">
							<ul class="nav nav-tabs card-header-tabs">
							  <li class="nav-item">
							    <%= link_to 'Show Post', post_path(post.id) %>
							  </li>
							  <li class="nav-item">
							    <a class="nav-link" href="#">Comments</a>
							  </li>
							</ul>
						</div>
						<div class="card-block">
							<h4 class="card-title"><%= post.title %></h4>
							<%= image_tag post.image, :class => "card-img-top"%>
							<p class="card-text"><%= post.content %></p>
							<a href="#">Show</a> 
						</div>
					</div>				
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/users/news_feed.html.erb
<div class="container container-table">
	<h2>News Feed</h2>
	<table class="table table-bordered">
		<tbody>
			<% @posts.each do |post| %>
				<tr>
					<div class="card cd" style="width: 40rem">
						<div class="card-header">
							<ul class="nav nav-tabs card-header-tabs">
							  
							  <li class="nav-item">
							    <a class="nav-link disabled" href="#"><%= post.user.first_name %></a>
							  </li>
							  <li class="nav-item">
							    <%= link_to 'Show Post', post_path(post.id) %>
							  </li>
							  <li class="nav-item">
							    <a class="nav-link" href="#">Comment</a>
							  </li>
							</ul>
						  	<%= post.created_at %>
						</div>
						<div class="card-block">
							<h4 class="card-title"><%= post.title %></h4>
							<%= image_tag post.image, :class => "card-img-top"%>
							<p class="card-text"><%= post.content %></p>
						</div>
					</div>				
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/users/show.html.erb
<h2>User details</h2>
<h3>Profile Picture</h3>
  <p>
    <%= image_tag @user.avatar.thumb.url %>
  </p>
<dl class="dl-horizontal">
	<dt><strong>Full Name</strong></dt>
	<dd><%= @user.full_name %></dd>
	<dt><strong>Email</strong></dt>
	<dd><%= @user.email %></dd>
</dl>


<%= link_to "Back", my_friends_path, class: 'btn btn-primary' %>

app/views/users/view_friend.html.erb
<h2>view friend page</h2>

<dl class="dl-horizontal">
	<dt><strong>Profile Picture</strong></dt>
	<dd><%= image_tag @current_friend.avatar %></dd>
	<dt><strong>First Name</strong></dt>
	<dd><%= @current_friend.first_name %></dd>
	<dt><strong>Last Name</strong></dt>
	<dd><%= @current_friend.last_name %></dd>
	<dt><strong>Email</strong></dt>
	<dd><%= @current_friend.email %></dd>

</dl>


<h3>Posts</h3>

<table class="table table-bordered">
	<tbody>
		<% @current_friend.posts.each do |post| %>
			<tr>
				<td><%= post.title %></td>
				<td><%= post.content %></td>
				<td><%= image_tag post.image.thumb %></td>
				<td><%= post.longitude %></td>
				<td><%= post.latitude %></td>
			</tr>
		<% end %>
	</tbody>
</table>