config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => "user/registrations" }

	namespace :api, defaults: {format: 'json'} do 
  		namespace :v1 do
  			resources :users, :controllers => {:my_friends => "user/my_friends"}
			resources :users, :controllers => {:show => "user/show"}
  			resources :posts, :controllers => {:create => "posts/create"}
        resources :friendships

        # map.resources :users, :path_names => {:my_friends => 'my_friends'}
        get 'my_friends', to: 'users#my_friends'
        get 'show', to: 'users#show'
        post 'create', to: 'posts#create'

  		end
  	end
  	
	resources :users, only: [:show]
	resources :friendships
	resources :posts

	root 'welcome#index'
	get 'my_friends', to: 'users#my_friends'
	get 'search_friends', to: 'users#search'
	post 'add_friend', to: 'users#add_friend'
	get 'my_posts', to: 'users#my_posts'
	get 'view_friend', to: 'users#view_friend'
	get 'news_feed', to: 'users#news_feed'
	post 'authenticate', to: 'authentication#authenticate'
	get 'test', to: 'welcome#test'
	get 'test2', to: 'welcome#test2'
	 #api auth token

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_left_Navbar.html.erb
<style>
.well {
    background-color: rgba(155,160,100,0.5) !important;
}
</style>
<div class="col-sm-3 well">
  <div class="well">
    <p><a href="#">My Profile</a></p>
    <% if current_user %>
      <%= image_tag current_user.avatar.thumb.url %>
    <% end %>
  </div>
  <div class="well">
    <p><a href="#">Interests</a></p>
    <p>
      <span class="label label-default">News</span>
      <span class="label label-primary">W3Schools</span>
      <span class="label label-success">Labels</span>
      <span class="label label-info">Football</span>
      <span class="label label-warning">Gaming</span>
      <span class="label label-danger">Friends</span>
    </p>
  </div>
  <div class="alert alert-success fade in">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
    <p><strong>Attention!</strong></p>
    You have friend requests
  </div>
  <p><a href="#">Request 1</a></p>
  <p><a href="#">Request 2</a></p>
  <p><a href="#">Request 3</a></p>
</div>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-default navbar-static-top navbar-inverse">
  <div class="container">
    <%= link_to 'Friend Club', root_path, class: "navbar-brand" %>
    <% if current_user %>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-collapse collapse navbar-responsive-collapse">
        <ul class="nav navbar-nav col-md-6">
          <li><%= link_to "News Feed", news_feed_path %></li>
          <li><%= link_to "My Posts", my_posts_path  %></li>
          <li><%= link_to "Friends", my_friends_path %></li>
          <li><%= link_to "Profile", edit_user_registration_path %></li>
          <li><%= link_to "Settings", edit_user_registration_path %></li>

          <li><%= link_to "New Post", new_post_path, class: "btn btn-xs btn-success", style: "color: blue" %></li>
        </ul>
        <ul class="nav navbar-right col-md-4">
          <li class="col-md-8 user-name text-right", style="color:white">
            <i class="fa fa-user"></i>
            <%= current_user.full_name.present? ? current_user.full_name : current_user.email %>
          </li>
          <li class="col-md-3 logout"><%= link_to("logout",destroy_user_session_path, class: "btn btn-xs btn-danger",method: :delete) %></li>
        </ul>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_right_Navbar.html.erb
<div class="col-sm-2 well">
  <div class="thumbnail">
    <p>Upcoming Events:</p>
    <img src="paris.jpg" alt="Paris" width="400" height="300">
    <p><strong>Paris</strong></p>
    <p>Fri. 27 November 2015</p>
    <button class="btn btn-primary">Info</button>
  </div>      
  <div class="well">
    <p>ADS</p>
  </div>
  <div class="well">
    <p>ADS</p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friend Club</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
  <style>
  .jumbotron{background-color: #FFFFFF!important; padding-top: 0px; padding-bottom: 0px;}
  .body{margin-top: 0px;}
  </style>

  </head>

  <body>
     <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>


      <div class="container">
        <div class="jumbotron" style="text-align: center;">
          <h1>Friend Club</h1>      
          <p>Helping friends share the joys of life.</p>
        </div>
      </div>


          <%= render 'layouts/navigation' %>
          <%= render 'layouts/left_Navbar' %>
          <div class="col-sm-7">
            <%= yield %>
          </div>
          <%= render 'layouts/right_Navbar' %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2017</p>
      </footer>

    </div> <!-- /container -->
  </body>
</html>